using Microsoft.Extensions.Logging;
using Wokki.Application.Common.Interfaces;

namespace Wokki.Infrastructure.Scheduling;

public sealed class ScheduleSuggestionOrchestrator(
    CpSatScheduleSuggestionService cpSat,
    ILogger<ScheduleSuggestionOrchestrator> logger) : IScheduleSuggestionOrchestrator
{
    public async Task<ScheduleSuggestionGenerationResult> GenerateAsync(
        Guid scheduleId,
        bool useAi,
        CancellationToken cancellationToken = default)
    {
        if (useAi)
        {
            logger.LogInformation(
                "Ignoring UseAi=true for schedule {ScheduleId}; schedule suggestions are generated by CP-SAT only",
                scheduleId);
        }

        return await cpSat.GenerateAsync(scheduleId, cancellationToken);
    }
}
